# Generated by Django 5.2 on 2025-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='site',
        ),
        migrations.AddField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
