# Generated by Django 5.2 on 2025-05-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_veiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='Ano',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Cor',
            new_name='cor',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Modelo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Preco',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='Acessorio',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(blank=True, related_name='veiculos', to='core.acessorio'),
        ),
    ]
