# Generated by Django 5.2 on 2025-05-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_ano_veiculo_ano_rename_cor_veiculo_cor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'cor', 'verbose_name_plural': 'cores'},
        ),
    ]
